services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: "3000"
    restart: unless-stopped
    command: >
      tunnel --protocol http2 --edge-ip-version 4 --no-autoupdate
      --url http://host.docker.internal:3000
